# Generated by Django 5.2.7 on 2025-10-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kcal', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('diet_tags', models.JSONField(default=list)),
                ('allergens', models.JSONField(default=list)),
                ('co2e', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
