# Generated by Django 5.2.7 on 2026-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_food_lang_alter_food_source_profile_intakelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='exclusions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
