# Generated by Django 5.2.7 on 2026-03-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_chatmessage_user_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coaching_plan',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='coaching_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
